baseurl = "https://vancanhuit.github.io"
title = "Canh Dinh"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

#[services]
#[services.disqus]
#disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "dracula"

[params]
  author = "Canh Dinh"
  info = "DevOps Engineer"
  description = "Personal blog"
  keywords = "blog,developer,personal"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

#[taxonomies]
  #category = "categories"
  #series = "series"
  #tag = "tags"
  #author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/vancanhuit/"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/canh-dinh-5077a6135/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
